export const FETCH_ALL_MESSAGES = "FETCH_ALL_MESSAGES";
export const FETCH_ALL_MESSAGES_SUCCESS = "FETCH_ALL_MESSAGES_SUCCESS";
export const FETCH_ALL_MESSAGES_FAILED = "FETCH_ALL_MESSAGES_FAILED";

export const FETCH_MESSAGE = "FETCH_MESSAGE";
export const FETCH_MESSAGE_SUCCESS = "FETCH_MESSAGE_SUCCESS";
export const FETCH_MESSAGE_FAILED = "FETCH_MESSAGE_FAILED";

export const ADD_MESSAGE = "ADD_MESSAGE";
export const ADD_MESSAGE_SUCCESS = "ADD_MESSAGE_SUCCESS";
export const ADD_MESSAGE_FAILED = "ADD_MESSAGE_FAILED";

export const UPDATE_MESSAGE = "UPDATE_MESSAGE";
export const UPDATE_MESSAGE_SUCCESS = "UPDATE_MESSAGE_SUCCESS";
export const UPDATE_MESSAGE_FAILED = "UPDATE_MESSAGE_FAILED";

export const DELETE_MESSAGE = "DELETE_MESSAGE";
export const DELETE_MESSAGE_SUCCESS = "DELETE_MESSAGE_SUCCESS";
export const DELETE_MESSAGE_FAILED = "DELETE_MESSAGE_FAILED";

export const SET_ACTIVE_MESSAGE = "SET_ACTIVE_MESSAGE";
